/// HTML output formatter — generates a standalone page with dark theme CSS.

use crate::models::*;
use super::OutputFormatter;

pub struct HtmlFormatter;

const CSS: &str = r#"
body { font-family: 'Segoe UI', Tahoma, sans-serif; margin: 0; padding: 20px;
       background: #1a1a2e; color: #e0e0e0; }
h1 { color: #00d4ff; border-bottom: 2px solid #16213e; padding-bottom: 10px; }
h2 { color: #ff6b6b; margin-top: 30px; }
h3 { color: #ffd93d; }
table { border-collapse: collapse; width: 100%; margin: 10px 0 20px; }
th { background: #16213e; color: #00d4ff; text-align: left; }
td, th { padding: 8px 12px; border: 1px solid #2a2a4a; }
tr:nth-child(even) { background: #0f3460; }
tr:nth-child(odd) { background: #1a1a3e; }
.critical { color: #ff4444; font-weight: bold; }
.warning { color: #ffa500; }
.info { color: #4da6ff; }
.ok { color: #44ff44; }
.site-header { background: #16213e; padding: 15px; border-radius: 8px;
               margin: 20px 0 10px; border-left: 4px solid #00d4ff; }
.site-header h2 { margin: 0; color: #00d4ff; }
.site-meta { color: #888; margin: 5px 0 0; }
pre { background: #0d0d0d; padding: 12px; border-radius: 5px;
      overflow-x: auto; color: #ffd93d; }
.summary { background: #16213e; padding: 12px 18px; border-radius: 5px;
           margin: 10px 0; display: inline-block; }
.outdated td { background: #3a0000 !important; }
.footer { margin-top: 30px; padding-top: 10px; border-top: 1px solid #2a2a4a;
          color: #666; font-size: 0.85em; }
"#;

impl HtmlFormatter {
    fn html_escape(s: &str) -> String {
        s.replace('&', "&amp;")
            .replace('<', "&lt;")
            .replace('>', "&gt;")
            .replace('"', "&quot;")
    }
}

impl OutputFormatter for HtmlFormatter {
    fn format_list(&self, sites: &[WpSite]) -> String {
        let mut rows = String::new();
        for site in sites {
            rows += &format!(
                "<tr><td>{}</td><td>{}</td><td>{}</td><td>{}</td><td>{}</td></tr>\n",
                Self::html_escape(&site.path.display().to_string()),
                site.version.as_deref().unwrap_or("?"),
                site.owner,
                site.group,
                site.permissions
            );
        }
        format!(
            r#"<!DOCTYPE html><html><head><meta charset="utf-8">
<title>WordPress Sites</title><style>{CSS}</style></head><body>
<h1>WordPress Installations</h1>
<table><tr><th>Path</th><th>Version</th><th>Owner</th><th>Group</th><th>Perms</th></tr>
{rows}</table>
<div class="footer">Generated by wp-scanner</div></body></html>"#
        )
    }

    fn format_versions(&self, sites: &[WpSite], latest_wp: &str) -> String {
        let mut rows = String::new();
        for site in sites {
            let ver = site.version.as_deref().unwrap_or("?");
            let outdated = site.is_wp_outdated(latest_wp);
            let class = if outdated { " class=\"outdated\"" } else { "" };
            let status = if outdated {
                "<span class=\"critical\">OUTDATED</span>"
            } else {
                "<span class=\"ok\">✓ OK</span>"
            };
            rows += &format!(
                "<tr{}><td>{}</td><td>{}</td><td>{}</td><td>{}</td><td>{}</td><td>{}</td></tr>\n",
                class,
                ver,
                site.owner,
                site.group,
                site.permissions,
                Self::html_escape(&site.path.display().to_string()),
                status
            );
        }
        format!(
            r#"<!DOCTYPE html><html><head><meta charset="utf-8">
<title>WordPress Versions</title><style>{CSS}</style></head><body>
<h1>WordPress Versions</h1>
<div class="summary">Latest version: <strong class="ok">{latest_wp}</strong></div>
<table><tr><th>Version</th><th>Owner</th><th>Group</th><th>Perms</th><th>Path</th><th>Status</th></tr>
{rows}</table>
<div class="footer">Generated by wp-scanner</div></body></html>"#
        )
    }

    fn format_report(&self, reports: &[SiteReport]) -> String {
        let mut body = String::new();

        for report in reports {
            let ver = report.site.version.as_deref().unwrap_or("unknown");
            let path = Self::html_escape(&report.site.path.display().to_string());

            body += &format!(
                r#"<div class="site-header"><h2>📦 {path} (WordPress {ver})</h2>
<p class="site-meta">Owner: {} | Group: {} | Permissions: {}</p></div>"#,
                report.site.owner, report.site.group, report.site.permissions
            );

            // Version check
            if let Some(latest) = &report.latest_wp_version {
                if report.site.is_wp_outdated(latest) {
                    body += &format!(
                        r#"<p class="critical">⚠ WordPress {ver} → {latest} available</p>
<pre>wp core update --path="{}"</pre>"#,
                        report.site.path.display()
                    );
                } else {
                    body += r#"<p class="ok">✓ WordPress is up-to-date</p>"#;
                }
            }

            // Plugins
            if let Some(plugins) = &report.plugins {
                body += "<h3>Plugins</h3>";
                if plugins.is_empty() {
                    body += "<p>No plugins found.</p>";
                } else {
                    body += "<table><tr><th>Plugin</th><th>Installed</th><th>Latest</th><th>Status</th></tr>";
                    let mut outdated_slugs = Vec::new();
                    for p in plugins {
                        let latest = p.latest_version.as_deref().unwrap_or("—");
                        let (class, status) = if p.is_outdated() {
                            outdated_slugs.push(p.slug.as_str());
                            (" class=\"outdated\"", "<span class=\"critical\">OUTDATED</span>")
                        } else if p.is_unknown() {
                            ("", "<span class=\"warning\">unknown</span>")
                        } else {
                            ("", "<span class=\"ok\">✓ OK</span>")
                        };
                        body += &format!(
                            "<tr{}><td>{}</td><td>{}</td><td>{}</td><td>{}</td></tr>",
                            class,
                            Self::html_escape(&p.name),
                            p.installed_version,
                            latest,
                            status
                        );
                    }
                    body += "</table>";

                    if !outdated_slugs.is_empty() {
                        body += &format!(
                            "<pre>wp plugin update {} --path=\"{}\"</pre>",
                            outdated_slugs.join(" "),
                            report.site.path.display()
                        );
                    }
                }
            }

            // Permissions
            if let Some(issues) = &report.perm_issues {
                body += "<h3>Permissions</h3>";
                if issues.is_empty() {
                    body += r#"<p class="ok">✓ No issues found</p>"#;
                } else {
                    body += "<ul>";
                    for issue in issues {
                        let class = match issue.severity {
                            Severity::Critical => "critical",
                            Severity::Warning => "warning",
                            Severity::Info => "info",
                        };
                        body += &format!(
                            r#"<li class="{class}"><strong>{}</strong> — <code>{}</code></li>"#,
                            Self::html_escape(&issue.issue),
                            issue.path.display()
                        );
                    }
                    body += "</ul>";

                    if !report.perm_fix_commands.is_empty() {
                        body += "<pre>";
                        for cmd in &report.perm_fix_commands {
                            body += &format!("{}\n", Self::html_escape(cmd));
                        }
                        body += "</pre>";
                    }
                }
            }

            // Backdoors
            if let Some(findings) = &report.backdoor_findings {
                body += "<h3>Backdoor Scan</h3>";
                if findings.is_empty() {
                    body += r#"<p class="ok">✓ No suspicious files found</p>"#;
                } else {
                    body += &format!(
                        r#"<p class="critical">⚠ {} finding(s)</p>"#,
                        findings.len()
                    );
                    body += "<table><tr><th>Severity</th><th>Pattern</th><th>File</th><th>Line</th><th>Snippet</th></tr>";
                    for f in findings {
                        let class = match f.severity {
                            Severity::Critical => "critical",
                            Severity::Warning => "warning",
                            Severity::Info => "info",
                        };
                        let line = if f.line > 0 {
                            f.line.to_string()
                        } else {
                            "—".to_string()
                        };
                        body += &format!(
                            r#"<tr><td class="{class}">{}</td><td>{}</td><td><code>{}</code></td><td>{}</td><td><code>{}</code></td></tr>"#,
                            f.severity,
                            f.pattern_name,
                            f.file.display(),
                            line,
                            Self::html_escape(&f.snippet)
                        );
                    }
                    body += "</table>";
                }
            }
        }

        format!(
            r#"<!DOCTYPE html><html><head><meta charset="utf-8">
<title>WP Scanner Report</title><style>{CSS}</style></head><body>
<h1>WP Scanner Report</h1>
{body}
<div class="footer">Generated by wp-scanner</div></body></html>"#
        )
    }
}
